import ddf.minim.*;

Minim minim;
AudioSample sa;
AudioSample sb;
AudioSample sc;
AudioSample sd;
AudioSample se;
AudioSample sf;
AudioSample sg;
AudioSample sh;
AudioSample si;
AudioSample sj;
AudioSample sk;
AudioSample sl;
AudioSample sm;
AudioSample sn;
AudioSample so;
AudioSample sp;
AudioSample sq;
AudioSample sr;
AudioSample ss;
AudioSample st;
AudioSample su;
AudioSample sv;
AudioSample sw;
AudioSample sx;
AudioSample sy;
AudioSample sz;

AudioSample[] sampleref = new AudioSample[0];